export enum EInquiryStatus {
  all = "All",
  draft = "Draft",
  open = "Open",
  sent = "Sent",
  not_shipped = "Not Shipped",
  delivered = "Delivered",
  quotation_converted = "Quotation Converted",
  partially_quotation_converted = "Partially Quotation Converted",
  partially_invoiced = "Partially Invoiced",
  partially_packed = "Partially Packed",
  partially_shipped = "Partially Shipped",
  partially_delivered = "Partially Delivered",
  packed = "Packed",
  partially_paid = "Partially Paid",
  paid = "Paid",
  not_paid = "Not Paid",
  not_packed = "Not Packed",
  shipped = "Shipped",
  invoiced = "Invoiced",
  not_invoiced = "Not Invoiced",
  overdue = "Overdue",
  void = "Void",
  cancelled = "Cancelled",
  pending = "Pending",
  accepted = "Accepted",
  rejected = "Rejected",
  expired = "Expired",
  confirmed = "Confirmed",
  closed = "Closed",
}

export const ESInquiryStatus = [
  EInquiryStatus.open,
  EInquiryStatus.overdue,
  EInquiryStatus.void,
  EInquiryStatus.partially_invoiced,
  EInquiryStatus.quotation_converted,
  EInquiryStatus.cancelled,
  EInquiryStatus.pending,
  EInquiryStatus.accepted,
  EInquiryStatus.rejected,
  EInquiryStatus.expired,
  EInquiryStatus.partially_shipped,
  EInquiryStatus.partially_paid,
  EInquiryStatus.not_paid,
  EInquiryStatus.confirmed,
  EInquiryStatus.paid,
  EInquiryStatus.sent,
  EInquiryStatus.not_shipped,
  EInquiryStatus.delivered,
  EInquiryStatus.not_invoiced,
  EInquiryStatus.not_packed,
];
